---
-  name: "Creating Basic MySQL Operator for Kubernetes Objects and Cluster Instances"
   hosts: tag_Name_Master
   tasks:
           -  name: "Create MySQL Operator CRD (Custom Resource Definition)"
              command: sudo kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
              register: crd_out

           -  name: "checking CRD output"
              debug: 
                 msg: "{{ crd_out }}"

           -  name: "Create MySQL Operator Object in Cluster"
              command: sudo kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml
              register: oper_out

           -  name: "Get MySQL Operator Deployment Data"
              command: sudo kubectl get deployment -n mysql-operator mysql-operator -o wide
              register: oper_deploy_out

           -  name: "checking Operator Deployment output"
              debug:
                 msg: "{{ oper_out }}"
              debug:
                 msg: "{{ oper_deploy_out }}"

           -  name: "Create Secret for MySQL Cluster"
              command: sudo kubectl create secret generic mypwds --from-literal=rootUser=root --from-literal=rootHost=% --from-literal=rootPassword="10aerodriguez2022"
              register: mypwd_out

           -  name: "Create Deployment File for Cluster"
              copy:
                  src: "./files/msql_cluster.yml"
                  dest: "/k8s/msql_cluster.yml"
                  force: yes

           -  name: "Run Deployment File for New MySQL Cluster"
              command: sudo kubectl apply -f /k8s/msql_cluster.yml
              register: msql_cluster_out

           -  name: "checking Cluster Deployment file"
              debug: 
                 msg: "{{  msql_cluster_out }}"

           -  name: "Get MySQL Service Description"
              command: sudo kubectl describe service mysqlcluster
              register: service_out

           -  name: "Get Database MySQL InnoDBCluster"
              command: sudo kubectl get innodbcluster
              register: innodb_out

           -  name: "checking MySQL Cluster Variables"
              debug:
                 msg: "{{ innodb_out }}"
           -  name: "checking services running"  
              debug:
                 msg: "{{ service_out }}"
   
