---
- hosts:  tag_Name_MasterU, tag_Name_NodesU
       gather_facts: no


       tasks: 
            - include:  1_initialize.yml
            - include:  2_configure_masteru.yml
            - include:  3_initialize_masteru.yml
            - include:  4_joinworkers.yml

