-  name: Initializing Master and Worker Nodes
   hosts:  tag_Name_MasterU, tag_Name_NodesU
   gather_facts: no
   vars_files:
         - vars.yml

   tasks:
      -  include_tasks:  ./ubuntucluster/1_initialize.yml
  

      -   include_tasks:  ./ubuntucluster/2_configure_masteru.yml
     
      -   include_tasks:  ./ubuntucluster/3_initialize_masteru.yml
  
      -  include_tasks:  ./ubuntucluster/4_joinworkers.yml

