apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sysbench
spec:
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app: sysbench
  template:
    metadata:
      name: sysbench
      labels:
        app: sysbench
    spec:
      containers:
        - name: sysbench
          image: perconalab/sysbench
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root_password
            - name: MYSQL_HOSTNAME
              value: 10.28.0.8
          command: ["bash"]
          args:
            - "-c"
            - |
              set -ex

              mysql \
                --host="${MYSQL_HOSTNAME}" \
                --port=3306 \
                --user="${MYSQL_USER}" \
                --password="${MYSQL_PASSWORD}" \
                -e 'CREATE DATABASE IF NOT EXISTS sbtest'

              sysbench /usr/share/sysbench/oltp_insert.lua \
                --db-driver=mysql \
                --mysql-host="${MYSQL_HOSTNAME}" \
                --mysql-port=3306 \
                --mysql-user="${MYSQL_USER}" \
                --mysql-password="${MYSQL_PASSWORD}" \
                --mysql-db=sbtest \
                --mysql_storage_engine=innodb \
                --tables=16 \
                --table_size=100 \
                prepare

              sysbench /usr/share/sysbench/oltp_read_write.lua \
                --rate=200 \
                --threads=16 \
                --report-interval=10 \
                --time=7200 \
                --events=0 \
                --rand-type=pareto \
                --db-driver=mysql \
                --mysql-host="${MYSQL_HOSTNAME}" \
                --mysql-port=3306 \
                --mysql-user="${MYSQL_USER}" \
                --mysql-password="${MYSQL_PASSWORD}" \
                --mysql-db=sbtest \
                --mysql_storage_engine=innodb \
                --table-size=0 \
                run
