- hosts: tag_Name_MasterU 
  become: yes
  gather_facts: false
  var_files:
          -  vars.yml
  tasks:
      - name: get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw
 
      - name: set join command
        set_fact:
              join_command: "{{ join_command_raw.stdout_lines[0] }}"
 
      - name: debugging lines
        debug:
            msg: "  {{  join_command }} "

      - name: "Adding token to a File"
        lineinfile:
             regexp: "^token: " 
             line: "token: {{ token_result.stdout }}"
             dest: "{{ file_dest }}"
             state: present
        delegate_to: localhost


- hosts: tag_Name_NodesU
  become: yes
  var_files:
          -  vars.yml
  tasks:
      - name: remove swap
        shell: "swapoff -a"
 
      - name: join cluster	
        shell:     "{{ token }}"    #"{{ hostvars['tag_Name_MasterU'].join_command }} >> node_joined.txt"
        args:
             chdir: $HOME
             creates: node_joined.txt
