apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  labels:
    app.kubernetes.io/component: pxc
    app.kubernetes.io/instance: scaling
    app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
    app.kubernetes.io/name: percona-xtradb-cluster
    app.kubernetes.io/part-of: percona-xtradb-cluster
  name: datadir-scaling-pxc-4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
