apiVersion: v1
data:
  init.cnf: |
    [mysqld]
    wsrep_debug=1
    max_allowed_packet=789M
    [sst]
    wsrep_debug=1
kind: ConfigMap
metadata:
  name: no-proxysql-pxc
  ownerReferences:
    - controller: true
      kind: PerconaXtraDBCluster
      name: no-proxysql
