- hosts: tag_Name_MasterU 
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: tag_Name_NodesU
  become: yes
  tasks:
  - name: HA Control DNS
    lineinfile:
      dest: /etc/hosts
      line: '10.96.0.2 kube-apiserver'
      search_string: 'kube-apiserver'
  - name: join cluster
    shell: "{{ hostvars['tag_Name_MasterU'].join_command }} --cri-socket=/run/containerd/containerd.sock >> node_joined.txt"
    args:
      chdir: $HOME
      creates: node_joined.txt
