-  name: Configure Master Node
   hosts: tag_Name_Master
   ignore_errors: yes
   vars_files:
       - vars.yml
   roles:
       - master


-  name: Configuring Worker Nodes
   hosts: tag_Name_Nodes
   ignore_errors: yes
   become: yes
   vars_files:
       - vars.yml
   roles:
       - nodes
