---
-  name: Creating a POD on this Cluster
   hosts: tag_Name_Master
   tasks:
           -  name: "Launching Pod"
              command: kubectl delete pod tomcat  
              register: pod

           -  name: "checking pod"
              debug: 
                 msg: "{{ pod }}"
