apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: backup1
spec:
  pxcCluster: some-name
  storageName: s3-us-west
status:
  completed: "2019-11-15T19:34:21Z"
  destination: s3://percona-jenkins-artifactory/big-data-test/cluster1-2019-15-11-19:30:13-full
  s3:
    bucket: s3://percona-jenkins-artifactory/big-data-test
    credentialsSecret: aws-s3-secret
    endpointUrl: https://s3.amazonaws.com
    region: us-west-2
  state: Succeeded
  storageName: s3-us-west
